# we need rpmbuild but it's unlikely to be whitelisted, according to
# https://github.com/travis-ci/apt-package-whitelist/pull/1700
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

language: scala
jdk: oraclejdk8

# but we can't run windows:packageBin, have to be on Windows for that
script:
- sbt -Dproject.version=2.12.0 universal:packageBin universal-docs:packageBin debian:packageBin rpm:packageBin

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
