# we need rpmbuild but it's unlikely to be whitelisted, according to
# https://github.com/travis-ci/apt-package-whitelist/pull/1700
sudo: required

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

language: scala
jdk: oraclejdk8

env:
  global:
    # PRIV_KEY_SECRET
    - secure: "NlnFqZs4mvCi63GqCdUNDsx9BoiyrjgoV0cUaKlhVYp49/qAMlEaKf6JABWy/oCHoWsTyysyLEtZLsWfjAyE4+FUHSzngNUHVFBbtyudA6aKQ7jMsqkcMM/K0h+ymnhHSv8bugc8jXKFgmfYk4YTi5dZgv8CAOSQFAFUaxVdYTY="

script:
  - admin/build.sh

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
